let arr = [10, 20, 30, 40, 50];
console.log(arr.length);
arr.push(60);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(5);
console.log(arr);
arr.shift();
console.log(arr);
console.log(arr.indexOf(30));
console.log(arr.includes(40));
console.log(arr.join("-"));
arr.reverse();
console.log(arr);
let newArr = arr.slice(1, 4);
console.log(newArr);
arr.splice(2, 1, 35);
console.log(arr); 